server:
  port: 8082
spring:
  application:
      name: demo-order
eureka:
  client:
     service-url:
         defaultZone: http://liaozp:111111@${eureka.instance.hostname}:8080/eureka/,http://liaozp:111111@${eureka.instance.hostname}:9001/eureka/
      register-with-eureka: true
      fetch-registry: true
  instance:
      hostname: 127.0.0.1
      ip-address:  localhost
      prefer-ip-address: true
      instance-id: ${spring.application.name}
ribbon:
